---
kind: pipeline
type: docker
name: CICD Pipeline Example
trigger:
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  - name: helloworld
    image: alpine
    commands:
      - echo "hello world"
  - name: install-packages
    image: node:lts-alpine
    commands:
      - npm install

  - name: lint
    image: node:lts-alpine
    commands:
      - cd my-app
      - npm run lint
  - name: build
    image: node:lts-alpine
    commands:
      - cd my-app
      - npm run build
