version: "3"

services:
  droneci:
    image: drone/drone:2
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./drone-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - drone_net

  drone_runner:
    image: drone/drone-runner-docker:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=droneci
      - DRONE_RPC_PORT=8081
      - DRONE_RPC_SECRET=super-secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=very-runner-such-fast
    links:
      - droneci
    depends_on:
      - droneci
    networks:
      - drone_net

networks:
  drone_net:
