services:
  droneci:
    image: drone/drone:2
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./drone-data:/data
    env_file: ".env"
    networks:
      - drone_net

  drone_runner:
    image: drone/drone-runner-docker:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 3000:3000
    env_file: ".env"
    network_mode: service:droneci

networks:
  drone_net:
